apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsapp
spec:
  selector:
    matchLabels:
      app: railsapp
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: railsapp
        image: 780171452443.dkr.ecr.us-east-1.amazonaws.com/railsapp:5e1f988
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
